title: Menlain
email: mzzmliang@gmail.com
realname: 张长恩
location: HeNan,China
description: "Hey"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  menlain
# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false

# Build settings
theme: minima
highlighter: rouge
permalink: pretty
paginate: 10
anchorjs: true


plugins: [jekyll-feed,jekyll-paginate]

# sass
sass:
  sass_dir: _sass
  style: compressed


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个简单的梦想：想成为一个合格的程序员"
sidebar-avatar: /assets/images/avatar.jpeg



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


